repos:

  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        args: [--safe, --quiet]
        python_version: python3.7

  - repo: https://github.com/RobbieClarken/isort
    rev: 2b48ad95e9ae84fe4b77c37bcfd9980c939b53b2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: flake8
