language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=bdd
install:
  - python3 -m pip install tox poetry
script:
  - tox
after_success:
  - tox -e coverage-report
